CC=gcc
CFLAGS=-I.

all:
	gcc -o schedule fcfs.c

run:
	./schedule tasks2

runverbose:
	./schedule tasks2 -verbose
mytest1:
	@echo "running test1"
	./schedule test1/tasks2
mytest2:
	@echo "running test2"
	./schedule test2/tasks2
	