CC=gcc
CFLAGS=-I.

all:
	gcc -o schedule edf_fcfs.c

run:
	./schedule tasksEDF_FCFS

runverbose:
	./schedule tasksEDF_FCFS -verbose

mytest1:
	@echo "running test1"
	./schedule test1/tasksEDF_FCFS 
mytest2:
	@echo "running test2"
	./schedule test2/tasksEDF_FCFS 
mytest3:
	@echo "running test3"
	./schedule test3/tasksEDF_FCFS 
mytest4:
	@echo "running test4"
	./schedule test4/tasksEDF_FCFS  