CC=gcc
CFLAGS=-I.

all:
	gcc -o schedule edf.c

run:
	./schedule tasksEDF

runverbose:
	./schedule tasksEDF -verbose
mytest1:
	@echo "running test1"
	./schedule test1/tasksEDF 
mytest2:
	@echo "running test2"
	./schedule test2/tasksEDF 
mytest3:
	@echo "running test3"
	./schedule test3/tasksEDF 